version: '3.8'
services:
  golang:
    build: ./docker/golang
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./app:/var/golang
    depends_on:
      - psql

  psql:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./psql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

  redis:
    image: redis:6.0.9-alpine3.12
    ports:
      - "6379:6379"